### GET ENV VARIABLES

GET http://localhost:3000/auth/env


### Signup User

POST http://localhost:3000/auth/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoibmF1bW92YWthdHJpbmthQGJlbW9uZS5jb20iLCJyb2xlIjoiSFIiLCJpYXQiOjE3NTEwMTIzMjcsImV4cCI6MTc1MTAxNTkyN30.YTBcC4Pfg615YDXAGsXazgnFJa-btFbOTp-juyQFzPs

{
    "firstName": "Khadijah",
    "lastName": "Smith",
    "email": "kadijahsmith28@casinolotte.com",
    "role": "WORKER"
}

### Login User

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "naumovakatrinka@bemone.com",
    "password": "mypassword123"
}

 # "password": "mypassword123"
 # "password": "StrngPwd_123"

### Send Email

POST http://localhost:3000/email/send-email
Content-Type: application/json

{
  "recipients": ["taiwooa.19@student.funaab.edu.ng"],
  "subject": "Test Email",
  "html": "This is a test email sent from the Nestjs application. <br> It is sent using the <a href=\"https://nodemailer.com/about/\">Nodemailer</a> package.",
  "text": "This is a test email sent from the Nestjs application. It is sent using the Nodemailer package."
}


### RESET PASSWORD

POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
 "email": "yaminahouti@taptoplab.com"
}

### Activate Account

POST http://localhost:3000/auth/activate
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthZGlqYWhzbWl0aDI4QGNhc2lub2xvdHRlLmNvbSIsInR5cGUiOiJhY3RpdmF0aW9uIiwiaWF0IjoxNzUxMDEyMzgxLCJleHAiOjE3NTEwMTU5ODF9.kMnm7p_PxShsbXal_X3r8qOhcxxaduMM9HyIuoLSpD8",
  "password": "mypassword123"
}
